### ISSUE TITLE
Error to access account

### ISSUE THREAD

**Issue by Narcizos** [limontec/WhatsApp-GDrive-Downloader#1]

**Comment by limontec** [comment]
Olá, você apagou a descrição quando editou. Mas resumindo, foi fornecido junto ao error as possíveis soluções. Desative 2FA da sua conta e depois acesse https://accounts.google.com/DisplayUnlockCaptcha e permita acesso, em seguida rode a ferramenta novamente utilizando sua senha normalmente. Gosto de lembrar que esses tipos de problemas devem ser relatado no repositório do Whapa uma vez que estamos utilizando a biblioteca deles, essa ferramenta aqui serve apenas como uma interface web para utilizar a função de download do backup presente na ferramenta Whapa. Portanto solicito que somente abrem um issue referente a error no script escrito para o Colab.
