### ISSUE TITLE
It doesn't work anymore , does it ? 

### ISSUE THREAD

**Issue by el5arsawi** [limontec/WhatsApp-GDrive-Downloader#3]
i have tried on my own account and it says file not found any more ,it worked fine a week ago , tried it with 2 different gmails.

**Comment by limontec** [comment]
Hi, thanks. I fix a recent error, and I tested right now and it is working.

**Comment by el5arsawi** [comment]
Tested and working fine now ,ty alot

**Comment by Aridetta** [comment]
I tried in on both of my accounts and it says 'file not found'.
How do I fix this?

**Comment by limontec** [comment]
> I tried in on both of my accounts and it says 'file not found'.
> How do I fix this?

So there is no backup on your Google Drive account with the number you typed. Try run with the phone number field empty, so it will show you all phone numbers with backup in your account.

**Comment by Aridetta** [comment]
> > I tried in on both of my accounts and it says 'file not found'.
> > How do I fix this?
> 
> So there is no backup on your Google Drive account with the number you typed. Try run with the phone number field empty, so it will show you all phone numbers with backup in your account.

I tried your suggestion. The same number I used appeared and the backup information connected to that number was the same. My problem is when I clicked download all, it would start the process, and upon completion, the 'file not found' error pops up.

**Comment by limontec** [comment]
> > > I tried in on both of my accounts and it says 'file not found'.
> > > How do I fix this?
> > 
> > 
> > So there is no backup on your Google Drive account with the number you typed. Try run with the phone number field empty, so it will show you all phone numbers with backup in your account.
> 
> I tried your suggestion. The same number I used appeared and the backup information connected to that number was the same. My problem is when I clicked download all, it would start the process, and upon completion, the 'file not found' error pops up.

Fixed. But, if your download does not start, download the file manually from the directory in the left corner. You will see a .zip file with your number, so right click > download.
