### ISSUE TITLE
mv: cannot stat '/content*/files/whatsapp_backup_*.zip': No such file or directory File not found!

### ISSUE THREAD

**Issue by pinnakkkk** [limontec/WhatsApp-GDrive-Downloader#4]
so I have about 2.2gb of backup which I KNOW FOR SURE, but I'm unable to restore it from whatsapp throws and error like:
![1](https://user-images.githubusercontent.com/52191876/184504042-7695186c-9eff-4e89-a7b3-e2b52444d1e5.jpg)
 
and using your script i get:
error: mv: cannot stat '/content919223424425/files/whatsapp_backup_919223424425.zip': No such file or directory File not found!

**Comment by limontec** [comment]
You need the same phone number to decrypt the backup or you are using a whatsapp version that doesn't support the encrypted version of the backup but I not sure. Maybe the backup file downloaded is corrupted  ...

**Comment by pinnakkkk** [comment]
> You need the same phone number to decrypt the backup or you are using a whatsapp version that doesn't support the encrypted version of the backup but I not sure. Maybe the backup file downloaded is corrupted ...

I'm using the same phone number and my whats app is up to date. i did get my media files back but for some reason the chats are still missing

**Comment by limontec** [comment]
> 

You need to use the same or approached version used when you did the backup. Maybe the updated whatsapp version doens't support the version of the encrypted chat you have.

**Comment by limontec** [comment]
About "error: mv: cannot stat '/content91999999999/files/whatsapp_backup_919223424425.zip': No such file or directory File not found!"
LOL fixed on v0.1.1
